TrajectoryPlannerROS:
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 10.0
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 20.0
  min_vel_theta: -20.0
  min_in_place_vel_theta: 0.05

  holonomic_robot: false

  meter_scoring: true
