# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from taskgen3/Task.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Task(genpy.Message):
  _md5sum = "61469da423d711030840b17fc9caf72f"
  _type = "taskgen3/Task"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 task_id
float64 deadline
float64 x_position
float64 y_position
float64 z_orientation
"""
  __slots__ = ['task_id','deadline','x_position','y_position','z_orientation']
  _slot_types = ['uint16','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_id,deadline,x_position,y_position,z_orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Task, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.task_id is None:
        self.task_id = 0
      if self.deadline is None:
        self.deadline = 0.
      if self.x_position is None:
        self.x_position = 0.
      if self.y_position is None:
        self.y_position = 0.
      if self.z_orientation is None:
        self.z_orientation = 0.
    else:
      self.task_id = 0
      self.deadline = 0.
      self.x_position = 0.
      self.y_position = 0.
      self.z_orientation = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H4d().pack(_x.task_id, _x.deadline, _x.x_position, _x.y_position, _x.z_orientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.task_id, _x.deadline, _x.x_position, _x.y_position, _x.z_orientation,) = _get_struct_H4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H4d().pack(_x.task_id, _x.deadline, _x.x_position, _x.y_position, _x.z_orientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.task_id, _x.deadline, _x.x_position, _x.y_position, _x.z_orientation,) = _get_struct_H4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H4d = None
def _get_struct_H4d():
    global _struct_H4d
    if _struct_H4d is None:
        _struct_H4d = struct.Struct("<H4d")
    return _struct_H4d
